resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/clediscorde/BookSuggestion.git
    branch: master

- name: pws
  type: cf
  source:
    api: https://api.run.pivotal.io
    organization: caledi-org
    username: deploy@caledi.ca
    password: Deploy@123
    skip_cert_check: true
    space: development
    skip_cert_check: true

jobs:
- name: build
  public: true
  plan:
  - get: source-code
    trigger: true
  - task: build
    file: source-code/ci/build.yml
  - put: pws
    params:
        manifest: source-code/manifest.yml
        path: source-code