---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
  - name: source-code

outputs:
  - name: build-output

run:
  path: "source-code/mvnw"
  args: ["-f", "source-code/pom.xml", "clean", "package"]

params:
  MAVEN_BASEDIR: source-code